### ISSUE TITLE
Little followups to #1029

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#1033]
I won't be working on IBAMR next week so I don't have time to tackle these immediately. I encourage the users of the heart model to give things a try :)
- [ ] libMesh's constraint implementation doesn't do a good job selecting the diagonal value for a constrained dof - I used `MatView` to take a look and it appears that it uses some integer instead of the old diagonal value. This messes up the conditioning of the mass matrix. We should replace the diagonal value with a better value (e.g., the value on the main diagonal of an unconstrained dof) to fix this.
- [ ] We should upgrade an example to use finite element AMR.
- [ ] We should update the documentation to explain that FE AMR can only be done before the systems are set up. (getting it to work during time evolution is another beast altogether)
- [ ] We should take a second look at the nodal quadrature tests and make sure that we get the same result when we use standard quadrature with QTRAP. To check this we will have to modify the mass matrix quadrature rule used in FEProjector. Fortunately, once we have the test output, we can save it and not worry about making permanently invasive changes to that class.

**Comment by drwells** [comment]
It might also help to use the diagonal (unconstrained) mass matrix as a preconditioner.

**Comment by drwells** [comment]
I checked as a part of #1049 that we do get the same results with the current implementation as we do with `QTRAP`.
