### ISSUE TITLE
Multilevel IBFE support

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#1112]
We talked about this a bit on slack and it's worth summarizing the status quo here.

The main goal is to let different `Elem`s interact with different levels in the patch hierarchy. The main application of this at the moment is putting valves in the heart model on some extra-special level while big structures are on a coarser level.

Users should be able to enable this feature by adding a new section to their input file:
```
IBFEMethod {
   // ... normal stuff goes here

   // this part is new
   FEDataManager {
      block_ids_on_levels {
         level_0 = // nothing on level 0
         level_1 = 100, 110 // big structures that aren't that dynamic are in the middle
         level_2 = // everything else on level 2
      }
   }
}
```
the idea is that we can keep backwards compatibility by assigning everything to the finest level by default. Unlike sidesets, block ids are unique to an element.

Here is our progress so far:
- [x] Give FEDataManager an input database (#1089)
- [x] Cleanup `FEDataManager` so that we do not need to worry about almost half a dozen constructors (#1093, #1104)
- [x] Modify `FEDataManager`'s data structures so that we loop over all levels instead of just the finest level (#1108)
- [x] Implement the `block_ids_on_levels` (or `subdomain_ids_on_levels`: the terminology isn't that important) input database and set up an appropriate data structure inside `FEDataManager` to store it (#1113)
- [x] Implement a function in FEDataManager that looks up what level an element should be on from its subdomain id (#1113)
- [x] Reimplement cell tagging based on what level an element should be on (#1119).
- [x] Reimplement the way we associate patches with elements (#1123).

At this point velocity interpolation should work automatically.
- [x] Correctly prolong quadrature point data so that levels are tagged correctly (#1127)
- [x] Implement some method for prolonging forces spread onto coarser patch levels up to finer patch levels as appropriate. This is the only step I don't know how to do yet (#1129)
- [x] Make sure things work when the mesh is *not* on the finest mesh level. (#1140)
- [x] Update the scratch hierarchy in IBFEMethod to work with multiple levels (this might be hard) (#1129, #1136)

**Comment by boyceg** [comment]
@drwells, here is the algorithm for force spreading:
```
f := 0  /// on all levels of the composite grid

for each level (coarsest to finest) {
    if (!coarsest level) {
        f_{level} := prolong f_{level-1}   /// prolong from next coarser level (if it exists)
    }
    f_{level} += S_{level} F_{level}   /// spread the local forces
}

**Comment by boyceg** [comment]
I think that this is implemented in `LDataManager` for point-based IB structures.

**Comment by boyceg** [comment]
Interpolation is the same but in the reversed order:
```
U_rhs := 0

for (level = finest_level; level >= 0; --level) {
    if (level < finest_level) {
        u_{level} := restrict u_{level+1}   /// restrict from next finer level (if it exists)
    }
    U_rhs += J_{level} u_{level}   /// interpolate the local velocities
}

U = M^{-1} U_rhs

**Comment by boyceg** [comment]
I think that it would be OK if the scratch hierarchy requires everything to be on a single level for now.

**Comment by boyceg** [comment]
I am not 100% sure that this will work. :-(

**Comment by boyceg** [comment]
But I am at least 90% sure. :-)

**Comment by boyceg** [comment]
I think that `LDataManager` is set up to allow user-specified restriction and prolongation. One thing I don't know is whether it is important for those to be discretely adjoint.

**Comment by drwells** [comment]
Are we going to run into problems where the operators may not be adjoint with this project?

**Comment by boyceg** [comment]
> Are we going to run into problems where the operators may not be adjoint with this project?

It may not matter. But we can surely figure out how to make adjoint pairs of operators if it does.

**Comment by boyceg** [comment]
> > Are we going to run into problems where the operators may not be adjoint with this project?
> 
> It may not matter. But we can surely figure out how to make adjoint pairs of operators if it does.

This is one of the reasons why I was working on an "RT0 coarsen" operator a while back. Probably time to revisit...

**Comment by drwells** [comment]
We may also want to find a better way to pass the prolongation operation along but I think the current approach is fine since about 100% of the time we are going to want to use RT0 anyway.
