### ISSUE TITLE
Speeding up regrids

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#1226]
It looks like regridding has become a bottleneck in IBFE. Overall, I think this is good news - we've fixed enough other problems that minor performance issues are now relatively major.

Some ideas for how we can improve our efficiency:
- [ ] cook up a branch which adds a large number of invasive timers to the regridding process so we can get a better idea of where we are spending our time.
- [ ] do a better job keeping the global vector of bounding boxes around - the elements don't move during regridding and calculating this thing repeatedly does cost something.
- [ ] tag cells based on element bounding boxes, not quadrature points
- [x] correctly transfer workload and tag data from the scratch hierarchy to the primary hierarchy. We never got around to this final fix in the scratch hierarchy stuff because it was hard (and regrids weren't a problem)
- [x] prune the list of active cell data indices by better using the scratch indices. We shouldn't communicate patch data we will never read.

**Comment by drwells** [comment]
The scratch hierarchy refactoring *should* fix most of this.
