### ISSUE TITLE
IIM merge plan

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#1234]
This summarizes the discussion from slack. The current state of IIM is:

### the good
- It's published
- It works
- It has examples
### the bad
- No tests (in the sense of the test suite, not just demo examples)
- It uses the predecessor to `LibmeshSystemVectors` or whatever we called it. The branch is old enough that it also has merge conflicts.
- Most of the implementation is in very large functions that aren't really extensible - it's very difficult to make changes to or maintain these 800-line functions
- libMesh has poor handling of surface meshes (which is a root cause of the massive function size) which makes the code hard to understand (not our fault, but its the reality of the situation)
### Verdict
- Lets rename it to IIMethod and merge roughly as-is. If we want to extend this in the future we need C1 surfaces anyway AFAIK so my worries about extensibility in that direction aren't that big of a deal. We can take some examples and chop them down to make them tests to verify that this class has consistent output (which helps us guard against libMesh regressions).

Lets track the state of that here. The rough plan now is
- [x] get whatever branch contains the changes up-to-date with master (i.e., squash and rebase)
- [x] copy and paste that class into `IIMethod`  - `IBFESurfaceMethod` should be unchanged by this effort
- [x] tests (we gotta do this first so we can verify other changes don't break anything)
- [ ] add examples from the papers into `examples/iim/`
- [x] convert some examples into basic tests
- [ ] use the new `LibMeshSystemIBVectors`
- [ ] some more parallel profiling to make sure there are not multi-part bottlenecks
- [x] documentation

We can meet to talk about it if people have further questions.

To get started - which branch contains the current working copy of the code?

**Comment by boyceg** [comment]
@AminKolah, can you work with @drwells to get the above tasks taken care of?

**Comment by drwells** [comment]
The tests mentioned in https://github.com/IBAMR/IBAMR/pull/1244#issuecomment-840764031 would be excellent to have.

**Comment by drwells** [comment]
I would like to get this done by the 0.9 release since a lot of people want to use it. I adjusted the 0.9 milestone back a full month. @AminKolah what can you commit to doing by August 1?

**Comment by AminKolah** [comment]
Working on it now...I'll try to finish the tests in the next few days.

**Comment by AminKolah** [comment]
I have tested this PR against all tests of the first IIM paper and double-checked convergence results / benchmark results. All examples are available on the paper repository at https://github.com/IBAMR/paper-IIM-weak_jumps , related to the publication at https://www.sciencedirect.com/science/article/pii/S0021999119305388 .  Is there anything else that needs to be done as far as verification/validation tests are concerned for this?

**Comment by boyceg** [comment]
Next we need short versions of some of these tests added to the main library.

**Comment by boyceg** [comment]
Let David know if it is not clear how to add the tests.

**Comment by AminKolah** [comment]
Currently, it doesn't seem like David has access to the paper repository.  So I think that's the first thing to do... Generating short versions of these tests/examples should be super straightforward but I can clarify/help with the examples if certain templates need to be generated for the main library.

**Comment by drwells** [comment]
I can see the repo, but I am still waiting on the tests we discussed in https://github.com/IBAMR/IBAMR/pull/1244#issuecomment-840764031. Let me know if you have questions on how to do it!

**Comment by AminKolah** [comment]
Can you be more specific about the tests? I see that you mentioned they need to take 30 sec or less according to this: https://github.com/IBAMR/IBAMR/pull/1244#issuecomment-840670856

**Comment by drwells** [comment]
Sure.

We have about 430 tests in IBAMR - the majority take less than a minute. They don't compute anything physically meaningful (most of the time for IBFE we have about 100 elements and do 50 time steps), but they validate that the output we get stays consistent over time. For example - many of the IBFE tests just validate that we end up with the same parallel DoF distribution and then quit.

A test consists of three things:
- input file. Usually the same as an example, but either the root processor writes a special `output` file or the log file should be named output. For instance, the parallel partitioning tests just send the partitioning to processor 0 and that writes a file named `output`and the log file is ignored.
- output file. The recorded output (again, either the log file or something we manually construct).
- test executable. These are usually based on examples (we have dozens of tests based on my favorite, i.e., `tests/IBFE/explicit_ex4.cpp`). Usually one executable is used with multiple tests. They need to be added to the automake file and CMakeLists.txt file.

The input and output files can have special commands in their names. For example, `explicit_ex4_2d.mpirun=4.input` will have a corresponding output file `explicit_ex4_2d.mpirun=4.output`, will use the executable named `explicit_ex4_2d`, and will be run by the test runner `attest` with 4 processors. Restarts behave similarly (look for input/output pairs with `restart` in the name to see how).

**Comment by drwells** [comment]
I'd like to move forward with this - we didn't make the last release window and we won't make the next one either unless we start accumulating patches.

I don't see tests (as in input and matching output files) in any branch here or in any of the IIM repos - we need those to move on to fixing the `Node` partitioning bug (and ultimately merging in `IIMethod`). Where are the tests? If they don't yet exist, what needs to happen next to get them into a PR?

**Comment by boyceg** [comment]
There are computational tests from the papers (in the paper repos), but there are not "unit tests".

**Comment by drwells** [comment]
That's a start. My impression from the conversations over the summer (e.g. https://github.com/IBAMR/IBAMR/pull/1244#issuecomment-840764031) was that @AminKolah would write tests. Is that right? If not, we should explicitly assign the work to someone.

**Comment by AminKolah** [comment]
I prepared most of these tests last night. I will add all them to the paper repo this evening when I go home and will make a PR to add them to the library.

**Comment by boyceg** [comment]
@drwells, @AminKolah, can we close this now? 😁

**Comment by AminKolah** [comment]
Yes since IIM has been merged inot master already? Maybe we should open a new one for adding some rigid and flexible tests?
