### ISSUE TITLE
Infrastructure Week (end of February)

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#1423]
I mentioned I would do this in another thread and I need to write down some todos somewhere.

We've run into a couple of silly problems recently due to insufficient CI coverage, including:
- examples don't compile with autotools
- examples don't compile with CMake
- bug with older versions of CMake
- things don't compile with older versions of clang (in particular when the compiler does not default to C++11 or newer)

Now that we have docker environments set up we should be able to expand our CI in a modular way (and use some machines at UNC). Some TODOs:
- [x] Set up another docker container that uses autotools
- [x] Verify that the current docker container compiles with optimizations on
- [x] Set up another docker container that uses all oldest supported versions of our dependencies (if we could use GCC 4.8.5 that would be even better)
- [x] enable `-Werror` to prevent silly stuff like unused variables coming through
- [ ] Set up clang-format
- [x] Compile tests and examples without libMesh

**Comment by abarret** [comment]
Our sys admin apparently doesn't have enough to do, so we have installed every clang release since 3.4 and every gcc release since 4.4. If there's something I can do with all these things available, let me know.

**Comment by drwells** [comment]
Can they set up stuff that will run at UNC or as GitHub actions?

**Comment by boyceg** [comment]
Nice. Can you post some documentation (in the wiki?) on Docker and/or sccache?
