### ISSUE TITLE
The draft, and actually writing some tutorial programs

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#1650]
We need to make it easier for new people to get started with IBAMR. A good way to do this is to have a curated set of tutorial programs with inlined explanations of what is going on in the doxygen documentation.

I'm drafting all eligible (i.e., not presently writing their thesis) graduate students and postdocs using IBAMR here at UNC to help me in this task - they will do most of the tutorial writing. The first thing to do here is to resurrect the doxygen deployment scripts which have been offline for quite some time - see #1649.

**Comment by drwells** [comment]
Something to add here is documentation on how to handle paraview support. We got this shell script on the mailing list:

```sh
#!/bin/bash

VizPath="./viz_IB3d_$1/*/"                          #data folder path
OutFileName="./viz_IB3d_$1/paraview.samrai.series"  #output file
declare -a arrdata=()                               #declare array for data
declare -a arrfolder=()                             #declare array for folder names
count=0                                             #counter for probe date
arrdata+=0                                          #add a zero in the beginning for probe data.
arrfolder+=($(ls -d $VizPath))                      #get folder names from VizPath

if test -f "$OutFileName"; then                     #if outputfile exist, delete it.
    rm "$OutFileName"
fi
arrfolder=( $(printf "%s\n" "${arrfolder[@]}" | sort -V) ) ## this is needed to sort the folders in 'natural' order
printf "{\n" >> $OutFileName
printf "  \"file-series-version\" : \"1.0\",\n" >> $OutFileName
printf "  \"files\" : [\n" >> $OutFileName

for i in "${arrfolder[@]}"
do
   var=$(echo $i | rev | cut -d'/' -f-2 | rev) #reformat string with folder names
   var2="${var}summary.samrai"                 #add summary.samrai to folder name strings
   time="${arrdata[$count]}"                   #get time value
   printf "    { \"name\" : \"./$var2\", \"time\" : $count }, \n"  >> $OutFileName #time will be 0,1,2,3 ….
    (( count++ ))
done
printf "  ]\n" >> $OutFileName
printf "}" >> $OutFileName

#done
```
we should clean it up a bit and bundle it in IBAMR proper (with an attribution to Jonas).

**Comment by drwells** [comment]
See also #1642 for some more things which could be better documented.

**Comment by drwells** [comment]
Another long-term thing to think about (related to this) is that we need some more IBAMR developers. There are a bunch of outstanding PRs - we all only have so much time to work on these things. My schedule is a bit freer this month than in October but there's stuff outstanding from August and September which is not good.

**Comment by drwells** [comment]
Lets clean this up in time for 0.17. TODOs:
- [ ] clean up the doxygen deployment process - this should be doable from inside the build system (#1150)
- [ ] support modules (see also how Cardinal does this) (#410)
- [ ] consolidate the learning-IBAMR repository into the manual
- [ ] consolidate anything Laura Miller did (see the repositories here: https://github.com/fairyflies9) into this manual too
