### ISSUE TITLE
Use clang-format

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#337]
Lets summarize some of the topics from the email discussion here so that things don't get lost.

It would be nice to run `clang-format` on IBAMR instead of us worrying about doing manual indentation. Here is a brief list of things that need to happen
- [x] agree on a `.clang-format` list of style rules
- [x] Teach Jenkins how to check PRs for style compliance
- [x] Possibly set up Jenkins to append style-fix commits to PRs. Perhaps we can do 'Jenkins reindent this please' or something similar? Alternatively, Jenkins could generate a patch file containing the indentation fixes.
- [ ] steal deal.II or MongoDB (or something similar) scripts for running clang-format in an intelligent way
- [x] push the button and reformat all non-bundled code

**Comment by boyceg** [comment]
I think it would be useful to get Jenkins or Travis set up to suggest reformatting for folks who are not running the `clang-format` git precommit hook.

**Comment by abarret** [comment]
> I think it would be useful to get Jenkins or Travis set up to suggest reformatting for folks who are not running the `clang-format` git precommit hook.

I started a Jenkins job to do this, but then I went back to working on other things before finishing it. I'll see where it's at and try to finish it tomorrow.

**Comment by abarret** [comment]
I added a Jenkins PR job if someone wants to take a look at it before I enable it.

It's designed to run `clang-format` on all the changed files and then emails a patch to all the users in the PR.

**Comment by drwells** [comment]
We should probably run clang-format ourselves on `master` before turning this on. I will take a look.

**Comment by drwells** [comment]
@abarret What version of clang format did you set up to run on Jenkins?

**Comment by abarret** [comment]
I just used whatever was already on the server. Looks like it is version 3.8. I can build a newer one though.

**Comment by drwells** [comment]
This is a duplicate of #1299 - lets move it there.
