### ISSUE TITLE
The 0.4 Release

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#424]
The current situation with C++ version support causes confusing compilation in 0.3.0 that were just fixed for 1.0 (see #423). I believe that we can solve this with the same approach by making C++11 support optional, but the default: i.e., let libMesh detect C++11 support if it is available (and do not instruct users to provide any flags like `--disable-cxx11` or `--disable-unique-ptr`). This should be compatible with versions of libMesh compiled with those flags anyway: we never assume (on 0.3.0) that `libMesh::UniquePtr` is `std::unique_ptr`, so compiling IBAMR with a newer language standard should work (I'll check this).

Can anyone else think of fixes that should go into this release?

**Comment by boyceg** [comment]
Perhaps all of the performance fixes that we are currently throwing into master? :-D

**Comment by drwells** [comment]
Honestly, I think thats the right thing to do: we aren't close to pulling the trigger on the SAMRAI 3 transition and we have made a lot of progress on improving IBAMR since the 0.3 release. It would make sense to do another major release that requires C++11 with what we have (and the rest of #436) and any other imminent fixes. We should aim to get that out in February.

**Comment by drwells** [comment]
Given that #427 exists I will try to find time to put out the new release this week once the partitioner code is merged in.

**Comment by drwells** [comment]
Lets get this done this week since people keep having C++14 issues. Here is the checklist:
- [ ] Finish partitioning (i.e., review and merge #479)
- [ ] Use FECache in FEDataInterpolation (see #482)
- [ ] Improve the performance of SystemDofMapCache (i.e., review and merge #481)

**Comment by drwells** [comment]
@jabrown893 Will you be around this afternoon? It would help me out if you could download the release candidate (which is not yet released) and check that it compiles and runs on a mac.

**Comment by jabrown893** [comment]
@drwells I will be around kind of intermittently. I have an appt. to give blood at 2:45.

**Comment by drwells** [comment]
@xxjaehoxx To the best of my knowledge we were not able to get things working with commits predating 0.3, so I think we should go ahead with the release without this patch. We can always release 0.6 later if we figure it out.

**Comment by xxjaehoxx** [comment]
This sounds good to me!

**Comment by drwells** [comment]
There is still a lot to do with #418, so lets wrap things up as-is.

**Comment by drwells** [comment]
I created the branch: see https://github.com/IBAMR/IBAMR/tree/IBAMR-0.4

**Comment by drwells** [comment]
The first release candidate is out. I'll continue to push minor changes without waiting for review.

@jabrown893 Could you take a look to make sure this compiles and runs on macs?

**Comment by jabrown893** [comment]
@drwells It's good on my mac!

**Comment by drwells** [comment]
The release is out and the documentation has been updated so lets close. Nice work everyone :tada:
