### ISSUE TITLE
Avoid calling FE::reinit when possible.

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#436]
The heart solver (with the afterload 10 benchmark) spends about 20% of its time calling `libMesh::FE::reinit`: unfortunately, specifying exactly what needs to be recomputed to libMesh is a bit tricky so we end up doing a lot of work there. In other benchmarks that have thicker structures (e.g., IBFE/explicit/ex4) we spend nearly half of our time calling this function. I'll have to do some more profiling to see where we are with the full heart model.

There is a bunch of stuff we can do to fix this:
- [x] A lot of the calls to `reinit` come from changing quadrature rules. We should just cache multiple `FE` objects (one per quadrature rule) to get around this. This is mostly done (see #437). This speeds up the first part of `interpWeighted` where we only need the function values.
- [x] We can get the `JxW` values by using `FEMap`. We should implement a similar cache strategy here: `FEMap` only depends on details of the finite element space (FE order, FE family) and the quadrature rule, so we can avoid recomputing everything but the Jacobians if we have cache here that uses the same strategy.
- [x] There are a few places where we build a new `Quadrature` object, but we only need the quadrature rule and number of points. We should clean that up too.
- [ ] Add caches to `IBTK::FEDataInterpolation`.

**Comment by boyceg** [comment]
`FEMap` _does_ use the element geometry for evaluating any quantities in "physical" coordinates. It does not depend on only the FE order / FE family. In particular, for `JxW` and derivatives of shape functions, it needs to know the mapping from the reference element to the physical configuration of the element.

**Comment by drwells** [comment]
@boyceg I think you're right but we need to be careful: `FEMap::init_reference_to_physical_map` does something with the FE order and type, and we do call it: however, I am pretty sure the data it computes is not read again.

**Comment by drwells** [comment]
FEDataInterpolation takes up only a small amount of the total run time (it totals at 5%, while something like `interpWeighted` is closer to 50%) and is not a massive source of bottlenecks like `spread` is, so I think we should close this for now: the 'high priority' part of easy to implement performance improvements is done. I'll open a separate issue for it like the `JxW` calculations.

We lowered the total number of cycles executed from 465 billion to 339 billion in the default settings for `IBFE/explicit/ex4/main3d` so I am declaring victory.

**Comment by drwells** [comment]
Quick update, for anyone following this thread: @cpuelz just reported that the heart model is running about 2x faster now that these are in :tada: :tada: :tada:

We should keep using callgrind to improve performance. I will open more issues if I come across more bottlenecks that are straightforward to fix.

**Comment by lindsayad** [comment]
@drwells We talked at the petsc-users meeting last week. It looks like you've already hit on most of the possible points for reducing calculations done in `FEMap`. We do most of our calculations in `FEMap` dependent on whether you've requested `JxW` or `dphi` and these quantities will obviously change if your element geometry changes (in the physical space). It looks like you've already hit on caching. It looks like @boyceg is an active participant in libmesh/libmesh#890.

Is there still something you would like on the libmesh side?

**Comment by drwells** [comment]
@lindsayad Thanks for following up on this. Its good to hear from you. One thing that would help here would be if we could avoid recomputing shape function values (i.e., `FEBase::phi`) for translation invariant elements since this value doesn't ever change.

I cannot remember exactly what I told you before so I will describe the problem here too. Setting up the load vector for an L2 projection was (before adding a bunch of caches) extremely expensive since we are using a lot of quadrature points (something like 100 per cell in 3D even with low-order elements) *and* the number of quadrature points varies per cell. Hence just calculating the values of the basis functions at the quadrature points is expensive. Part of this is due to the variable number of quadrature points per element (a problem from IBAMR) but the other part is due to the recomputation of `phi`.
