### ISSUE TITLE
IBAMR 0.5

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#630]
I am going to open an issue for this to keep track of what we want to get done.

We are only about halfway through the NWT branch. Since it has taken at least a day to address each of the bullet points in #546 I don't think its realistic to get this done (though we did make a good dent in it!) this week.

I would like to put up a release candidate late on Wednesday, which means we need to have all major changes merged by tomorrow afternoon. This way we can do bug and compiler warning fixes on Thursday and Friday if necessary.

I am assuming that after this release we will also do a 0.6 release before we pull the trigger and switch to SAMRAI 3. Hence, I think its best we just go with approximately what we have now and plan on getting the rest of these branches tackled by the end of summer.

# Things to do for this release
## things to do on master
- [x] Close the open doc issues in the `ibamr.github.io` repo
- [x] Check that with recent changes (e.g., #601) to the build system we can still use the template Makefile to compile IBAMR applications (see #641)
- [x] ~~finish #569 ~and excise all gtest code~. This isn't critical w.r.t. multiphysics or performance, but we should get this done so that we can stop writing those unused test stubs and have a clean break in the test suite. *Update*: lets keep gtest for compatibility, but I am still aiming at converting the last few tests.~~ Not critical, so skipped. I suspect not many people are going to use either test suite right now.
- [x] Check that we can compile with and without libMesh (I am pretty sure that this is currently broken) (see #642)
- [x] Run clang-format on all examples, tests, and source flies (I forgot to run it on `IndexUtilities.h` and `IndexUtilities-inl.h` recently) (#633)
- [x] check that all recent PR's of note have a corresponding changelog entry
- [x] collate all changelog entries into a single header
## after branching
- [x] update `VERSION` to 0.5.0
- [x] do a lot of testing
- [x] put out a release candidate
- [x] check that recommended settings squelch the majority of warnings on macs and also on various Linux distributions
- [x] put out the release
- [x] celebrate!

**Comment by drwells** [comment]
@boyceg can overrule me on this, but I don't think we are close to getting NWT or #637 done. I propose we wrap up what we have this week and plan on doing another release at the end of August with those new features.

**Comment by boyceg** [comment]
Let me try to finish it up this week.

**Comment by drwells** [comment]
@boyceg What is your status on NWT?

**Comment by boyceg** [comment]
Ummm.

**Comment by drwells** [comment]
I think we are at the point where, if we want to keep to my original plan and do another release in late August [1] or early September then we should go ahead with what we have now. I will wrap up #635 and #646 and then put out a release candidate.

[1] I want to do another release coincident with the start of the semester so that some of @amneetb's incoming students have what they need (i.e., more large parts of NWT) to get to work.

**Comment by boyceg** [comment]
I think this is fine. We should be able to put out 0.6 in early-to-mid August with NWT and IBFESurfaceMethod, possibly along with updated viscoelastic fluid solvers and stress-splitting methods.

**Comment by drwells** [comment]
Let’s get the quadratic interpolation fixed and then leave the rest for later.  Converting tests is not critical (but it is tedious)

**Comment by amneetb** [comment]
NWT, ummmmm, umm, um,u...

**Comment by drwells** [comment]
This release has already been pushed back a ton. Unless we have more patches ready to go it’s going to have to wait.

**Comment by boyceg** [comment]
Let's go ahead and prepare to release 0.5. I have a pile of non-coding work that I _must_ do this week. I will try to get it done at the beginning of the week, so that I can do NWT at the end.

**Comment by drwells** [comment]
@abarret do you think that we can finish the quadratic thing today?

**Comment by drwells** [comment]
We made it this far without it. Lets pull the trigger!

**Comment by drwells** [comment]
The release is out and things seem to be in working order, so lets close.
